app/users/models.py
import os

from flask_login import UserMixin
from slugify import slugify
from sqlalchemy.event import listens_for

from app.extensions import bcrypt, db
from app.utils.common import create_safe_filename, remove_file, save_media_file
from app.utils.validators import is_extension_allowed
from config import Config


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), nullable=False, unique=True)
    email = db.Column(db.String(256), nullable=False, unique=True)
    password = db.Column(db.String(128), nullable=False)
    first_name = db.Column(db.String(64))
    last_name = db.Column(db.String(64))
    image = db.Column(db.Text, nullable=True, unique=True)
    slug = db.Column(db.String(32), nullable=False, unique=True)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._hash_password()
        self.create_slug()

    def _hash_password(self):
        self.password = bcrypt.generate_password_hash(self.password)

    def create_slug(self):
        self.slug = slugify(self.username)

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

    def update_image(self, image):
        filename = image.filename
        if filename and is_extension_allowed(filename):
            safe_filename = create_safe_filename(filename)
            save_media_file(directory=Config.USERS_MEDIA_DIR, file=image, safe_filename=safe_filename)

            remove_file(
                os.path.join(Config.UPLOAD_FOLDER, Config.USERS_MEDIA_DIR),
                self.image,
            )
            self.image = safe_filename

            db.session.commit()

    def __repr__(self):
        return f'<{self.username}>'


@listens_for(User, 'before_update')
def change_slug(mapper, connection, target):
    target.create_slug()

app/users/forms.py
from flask_login import current_user, login_user
from flask_wtf import FlaskForm
from wtforms import (BooleanField, EmailField, FileField, PasswordField,
                     StringField, SubmitField)
from wtforms.validators import (Email, EqualTo, InputRequired, Length,
                                ValidationError)

from app.extensions import db
from app.users.models import User
from app.utils.validators import is_object_exists


class RegistrationForm(FlaskForm):
    username = StringField(
        'username',
        validators=[InputRequired(), Length(min=4, max=32)],
        render_kw={
            'class': 'input input--auth',
            'placeholder': 'Enter username',
        },
    )
    email = EmailField(
        'email',
        validators=[InputRequired(), Email()],
        render_kw={
            'class': 'input input--auth',
            'placeholder': 'Enter email',
        },
    )
    password = PasswordField(
        'password',
        validators=[
            InputRequired(),
            Length(min=8, max=20),
            EqualTo('password_confirmation', message='Passwords do not match.'),
        ],
        render_kw={
            'class': 'input input--auth',
            'placeholder': 'Enter password',
        },
    )
    password_confirmation = PasswordField(
        'password_confirmation',
        validators=[InputRequired(), Length(min=8, max=20)],
        render_kw={
            'class': 'input input--auth',
            'placeholder': 'Enter password',
        },
    )
    submit = SubmitField('Sign Up', render_kw={'class': 'btn btn--form'})

    def validate_username(self, username):
        if is_object_exists(User, username=username.data):
            raise ValidationError('A user with this username already exists.')

    def validate_email(self, email):
        if is_object_exists(User, email=email.data):
            raise ValidationError('A user with this email already exists.')

    def create_new_user(self):
        username = self.username.data
        email = self.email.data
        password = self.password.data

        new_user = User(username=username, email=email, password=password)

        db.session.add(new_user)
        db.session.commit()


class LoginForm(FlaskForm):
    username = StringField(
        'username',
        validators=[InputRequired(), Length(min=4, max=32)],
        render_kw={
            'class': 'input input--auth',
            'placeholder': 'Enter username',
        },
    )
    password = PasswordField(
        'password',
        validators=[InputRequired(), Length(min=8, max=20)],
        render_kw={
            'class': 'input input--auth',
            'placeholder': 'Enter password',
        },
    )
    remember_me = BooleanField(
        'remember_me',
        render_kw={'class': 'form__checkbox'},
    )
    submit = SubmitField('Log In', render_kw={'class': 'btn btn--form'})

    def authenticate_user(self):
        user = User.query.filter_by(username=self.username.data).first()

        if user and user.check_password(self.password.data):
            login_user(user, remember=self.remember_me.data)
            return True
        return False


class ProfileForm(FlaskForm):
    username = StringField(
        'username',
        validators=[Length(min=4, max=32)],
        render_kw={
            'class': 'input input--profile',
            'placeholder': 'Enter username',
        },
    )

    first_name = StringField(
        'first_name',
        validators=[Length(max=64)],
        render_kw={
            'class': 'input input--profile',
            'placeholder': 'Enter first name',
        },
    )

    last_name = StringField(
        'last_name',
        validators=[Length(max=64)],
        render_kw={
            'class': 'input input--profile',
            'placeholder': 'Enter last name',
        },
    )

    image = FileField('image')

    submit = SubmitField('Change', render_kw={'class': 'btn btn--profile'})

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user and user != current_user:
            raise ValidationError('A user with this username already exists.')

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from app.users import controllers, routes

app/users/controllers.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required, logout_user

from app.extensions import db, login_manager
from app.users import bp
from app.users.forms import LoginForm, ProfileForm, RegistrationForm
from app.users.models import User
from app.utils.decorators import logout_required
from config import Config


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@bp.route('/login/', methods=['GET', 'POST'])
@logout_required
def login():
    form = LoginForm()
    if form.validate_on_submit():
        if form.authenticate_user():
            return redirect(url_for('main.index'))
        else:
            flash('The entered data is incorrect, please try again.', 'warning')
    return render_template('users/login.html', form=form)


@bp.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@bp.route('/registration/', methods=['GET', 'POST'])
def registration():
    form = RegistrationForm()
    if form.validate_on_submit():
        form.create_new_user()
        flash('You have successfully registered!', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/registration.html', form=form)


@bp.route('/profile/<string:slug>/', methods=['GET', 'POST'])
@login_required
def profile(slug):
    user = User.query.filter_by(slug=slug).first_or_404()

    if user != current_user:
        return abort(403)

    form = ProfileForm()

    if form.validate_on_submit():
        username = form.username.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        image = form.image.data

        if image:
            user.update_image(image)
        if username:
            user.username = username
        if first_name:
            user.first_name = first_name
        if last_name:
            user.last_name = last_name

        db.session.commit()

        flash('Profile successfully updated!', 'success')
    return render_template('users/profile.html', form=form, user=user, users_media_dir=Config.USERS_MEDIA_DIR, )

app/users/routes.py
from app.users.resources import UserApi, LoginApi, RegistrationApi
from app.extensions import api

api.add_resource(UserApi, '/users/me/')
api.add_resource(LoginApi, '/users/login/')
api.add_resource(RegistrationApi, '/users/registration/')

app/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="icon" href="{{ url_for('static', filename='img/icon.svg') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <title>{% block title %} Shortify {% endblock %}</title>
</head>
<body>
<div class="container-center bg-secondary">
  <div class="form-wrp">
    {% block form %} {% endblock %}
  </div>
</div>
</body>
</html>

app/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %} Shortify | Log In {% endblock %}

{% block form %}
  <form class="login-form" action="{{ url_for('users.login') }}" method="post">

    {{ form.hidden_tag() }}

    <h2 class="form__title">Log In</h2>
    {% if get_flashed_messages() %}
      <div class="flash flash--active">
        {% for message in get_flashed_messages() %}
          <div class="flash-content">
            <p class="flash__text">{{ message }}</p>
          </div>
        {% endfor %}
      </div>
    {% elif form.errors %}
      <div class="flash flash--error">
        <div class="flash-content">
          {% for field, errors in form.errors.items() %}
            {% for error in errors %}
              <p class="flash__text"><span class="flash__bold">{{ field|capitalize }}: </span>{{ error }}</p>
            {% endfor %}
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <hr class="divider">
    <div class="input-group">
      <label for="{{ form.username.id }}">Username:</label>
      {{ form.username }}
      <p class="form__text">Note that the username may be case-sensitive.</p>
    </div>
    <div class="input-group">
      <label for="{{ form.password.id }}">Password:</label>
      {{ form.password }}
    </div>
    <div class="input-group d-flex">
      {{ form.remember_me }}
      <label for="{{ form.remember_me.id }}">Remember me</label>
      <a class="form-link form-link--secondary ml-auto" href="#">Forgot password ?</a>
    </div>
    <hr class="divider">
    <div class="form-submit-wrp">
      {{ form.submit }}
      <p>
        Not registered ?
        <a class="form-link form-link--active" href="{{ url_for('users.registration') }}">
          Create your account
        </a>
      </p>
    </div>
  </form>
{% endblock %}

app/templates/users/profile.html
{% extends 'base.html' %}


{% block content %}
    <div class="profile-wrp">
      {% if user.image %}
        <img class="profile-img" src="{{ url_for('media', filename=users_media_dir + '/' + user.image) }}"
             alt="user_image" height="256" width="256">
      {% else %}
        <img class="profile-img" src="{{ url_for('static', filename='img/default_user_image.png') }}" alt="user_image"
             height="256" width="256">
      {% endif %}
      <h3 class="profile__username">{{ user.username }}</h3>
      {% if get_flashed_messages() %}
        <div class="flash flash--active">
          {% for message in get_flashed_messages() %}
            <div class="flash-content">
              <p class="flash__text">{{ message }}</p>
            </div>
          {% endfor %}
        </div>
      {% elif form.errors %}
        <div class="flash flash--active">
          <div class="flash-content">
            {% for field, errors in form.errors.items() %}
              {% for error in errors %}
                <p class="flash__text"><span class="flash__bold">{{ field|capitalize }}: </span>{{ error }}</p>
              {% endfor %}
            {% endfor %}
          </div>
        </div>
      {% endif %}
      <div class="profile-form-wrp">
        <form class="profile-form" action="{{ url_for('users.profile', slug=user.slug) }}" method="post"
              enctype="multipart/form-data">

          {{ form.hidden_tag() }}

          <div class="input-group">
            <label for="{{ form.username.id }}">Username:</label>
            {{ form.username(value=user.username) }}
          </div>
          <div class="input-group">
            <label for="{{ form.first_name.id }}">First name:</label>
            {% if user.first_name %}
              {{ form.first_name(value=user.first_name) }}
            {% else %}
              {{ form.first_name }}
            {% endif %}
          </div>
          <div class="input-group">
            <label for="{{ form.last_name.id }}">Last name:</label>
            {% if user.last_name %}
              {{ form.last_name(value=user.last_name) }}
            {% else %}
              {{ form.last_name }}
            {% endif %}
          </div>
          <div class="input-group">
            <label for="{{ form.image.id }}">Image:</label>
            {{ form.image }}
          </div>
          <div class="form-submit-wrp">
            {{ form.submit }}
          </div>
        </form>
      </div>
    </div>
{% endblock %}

app/templates/users/registration.html
{% extends 'users/base.html' %}

{% block title %} Shortify | Sign Up {% endblock %}

{% block form %}
  <form class="registration-form" action="{{ url_for('users.registration') }}" method="post">

    {{ form.hidden_tag() }}

    <h2 class="form__title">Sign Up</h2>
    {% if get_flashed_messages() %}
      <div class="flash flash--active">
        {% for message in get_flashed_messages() %}
          <div class="flash-content">
            <p class="flash__text">{{ message }}</p>
          </div>
        {% endfor %}
      </div>
    {% elif form.errors %}
      <div class="flash flash--error">
        <div class="flash-content">
          {% for field, errors in form.errors.items() %}
            {% for error in errors %}
              <p class="flash__text"><span class="flash__bold">{{ field|capitalize }}: </span>{{ error }}</p>
            {% endfor %}
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <hr class="divider">
    <div class="input-group">
      <label for="{{ form.username.id }}">Username:</label>
      {{ form.username }}
      <p class="form__text">Your username must be at least 4 characters up to a maximum of 32.</p>
    </div>
    <div class="input-group">
      <label for="{{ form.email.id }}">Email:</label>
      {{ form.email }}
    </div>
    <div class="input-group">
      <label for="{{ form.password.id }}">Password:</label>
      {{ form.password }}
      <p class="form__text">
        Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces or
        special characters.
      </p>
    </div>
    <div class="input-group">
      <label for="{{ form.password_confirmation.id }}">Confirm password:</label>
      {{ form.password_confirmation }}
    </div>
    <hr class="divider">
    <div class="form-submit-wrp">
      {{ form.submit }}
      <p>
        Already registered?
        <a href="{{ url_for('users.login') }}" class="form-link form-link--active">
          Login to your account
        </a>
      </p>
    </div>
  </form>
{% endblock %}